// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iczrgrgonwmiyrmoxtbz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImljenJncmdvbndtaXlybW94dGJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5MDcwMDAsImV4cCI6MjA2MTQ4MzAwMH0.M7gKbxlQEGobpauu4CtSFLcK73c60zgr2S8mz4fk1H8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);