
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import type { Json } from './types';

const SUPABASE_URL = "https://dmqkgahwnpvtzawncluv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRtcWtnYWh3bnB2dHphd25jbHV2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyNjI4MzksImV4cCI6MjA1NzgzODgzOX0.UE1CyrOqzyzfSVkq5krLK_WNxm2_2NZoFC8Y9ex7uow";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Define the HelpField type for the help information fields
export interface HelpField {
  id: string;
  title: string;
  content: string;
}

export interface SiteSettings {
  id?: string;
  site_name: string;
  page_title?: string;
  logo_url?: string | null;
  favicon_url?: string | null;
  primary_color: string;
  secondary_color: string;
  text_color: string;
  footer_text: string;
  support_available?: boolean;
  support_message?: string;
  support_info?: string;
  support_help_fields?: HelpField[] | Json; // Allow both HelpField[] and Json types
  created_at?: string;
}

// Define PriorityType as a literal union type
export type PriorityType = 'urgent' | 'medium' | 'normal';
